language: java

jdk:
  - oraclejdk8

before_script:
  - mkdir MineDoor
  - mv * MineDoor > /dev/null 2>&1
  - cp MineDoor/build.sh build.sh

script:
  - jdk_switcher use oraclejdk8
  - bash ./build.sh -n

after_script:
  - cat install.log